

INSERT INTO users (first_name, last_name, username, email, password, phone_number, is_blocked, is_admin)
VALUES
    ('Iliyan', 'Trenchev', 'user777', 'user777@email.com', 'password7', null, false, true),
    ('Ivan', 'Belev', 'user888', 'user888@email.com', 'password8',null, false, true),
    ('Aleksandar', 'Torhov', 'admin', 'user2@email.com', 'password2', null,false, true),
    ('John', 'Smith', 'jsmith', 'jsmith@email.com', 'password123',null, false, false),
    ('Mary', 'Johnson', 'mjohnson', 'mjohnson@email.com', 'password123',null, false, false),
    ('David', 'Brown', 'dbrown', 'dbrown@email.com', 'password123',null, false, false),
    ('Jennifer', 'Davis', 'jdavis', 'jdavis@email.com', 'password123',null, false, false),
    ('Michael', 'Wilson', 'mwilson', 'mwilson@email.com', 'password123',null, false, false),
    ('Sarah', 'Garcia', 'sgarcia', 'sgarcia@email.com', 'password123',null, false, false),
    ('James', 'Miller', 'jmiller', 'jmiller@email.com', 'password123',null, false, false),
    ('William', 'Taylor', 'wtaylor', 'wtaylor@email.com', 'password123', null,false, false),
    ('Karen', 'Anderson', 'kanderson', 'kanderson@email.com', 'password123', null,false, false),
    ('Charles', 'Martin', 'cmartin', 'cmartin@email.com', 'password123', null,false, false),
    ('Jessica', 'Moore', 'jmoore', 'jmoore@email.com', 'password123', null,false, false),
    ('Brian', 'Jackson', 'bjackson', 'bjackson@email.com', 'password123', null,false, false),
    ('Nancy', 'Lee', 'nlee', 'nlee@email.com', 'password123', null,false, false),
    ('Kevin', 'Harris', 'kharris', 'kharris@email.com', 'password123', null,false, false),
    ('Linda', 'Clark', 'lclark', 'lclark@email.com', 'password123', null,false, false),
    ('Steven', 'Lewis', 'slewis', 'slewis@email.com', 'password123', null,false, false),
    ('Emily', 'Allen', 'eallen', 'eallen@email.com', 'password123', null,false, false),
    ('Scott', 'Young', 'syoung', 'syoung@email.com', 'password123', null,false, false),
    ('Kimberly', 'King', 'kking', 'kking@email.com', 'password123', null,false, false),
    ('Jason', 'Wright', 'jwright', 'jwright@email.com', 'password123', null,false, false);


INSERT INTO posts (title, rating, content, user_id, create_time)
VALUES ('How to open account on Binance?', 5, 'This is the body of the post 1', 1, NOW()),
       ('NEW NFT Airdrops, hurry up!!!', 5, 'This is the body of the post 2', 2, NOW()),
       ('Saitama is a shitcoin or future of the crypto?', 1, 'This is the body of the post 3', 1, NOW()),
       ('Do not buy this NFT - SCAM alert!!!', 1, 'This is the body of the post 4', 1, NOW()),
       ('New ICO, airdrops for first 200 registered', 5, 'This is the body of the post 5', 2, NOW()),
       ('Will BTC finally replace fiat money?', 5, 'This is the body of the post 6', 2, NOW()),
       ('Top 10 Altcoins to invest in for 2022', 4, 'This is the body of the post 8', 3, NOW()),
       ('How to use DeFi platforms for passive income?', 5, 'This is the body of the post 9', 4, NOW()),
       ('Why Ethereum is the future of the blockchain?', 5, 'This is the body of the post 10', 5, NOW()),
       ('Is it too late to invest in cryptocurrency?', 2, 'This is the body of the post 11', 6, NOW()),
       ('Why Dogecoin is not a good investment?', 1, 'This is the body of the post 12', 7, NOW()),
       ('The rise of NFTs - what you need to know', 4, 'This is the body of the post 13', 8, NOW()),
       ('How to protect your cryptocurrency from theft?', 5, 'This is the body of the post 14', 9, NOW()),
       ('Why you should start accepting cryptocurrency payments', 4, 'This is the body of the post 15', 10, NOW()),
       ('The best hardware wallets for securing your crypto', 5, 'This is the body of the post 16', 11, NOW()),
       ('Why you should invest in a diversified crypto portfolio', 5, 'This is the body of the post 17', 12, NOW()),
       ('The environmental impact of cryptocurrency mining', 3, 'This is the body of the post 18', 13, NOW()),
       ('Why Bitcoin will remain the king of crypto', 5, 'This is the body of the post 19', 14, NOW()),
       ('How to avoid scams in the cryptocurrency space', 5, 'This is the body of the post 20', 15, NOW()),
       ('The best resources for staying up-to-date on crypto news', 4, 'This is the body of the post 21', 16, NOW()),
       ('Why stablecoins are important for the cryptocurrency ecosystem', 5, 'This is the body of the post 22', 17, NOW()),
       ('The potential of blockchain technology beyond cryptocurrency', 5, 'This is the body of the post 23', 18, NOW()),
       ('How to create your own cryptocurrency', 3, 'This is the body of the post 24', 19, NOW()),
       ('The future of decentralized finance (DeFi)', 5, 'This is the body of the post 25', 20, NOW()),
       ('Why smart contracts are the future of the legal industry', 4, 'This is the body of the post 26', 1, NOW()),
       ('How to earn passive income with staking', 5, 'This is the body of the post 27', 2, NOW()),
       ('Why you should invest in crypto mining stocks', 4, 'This is the body of the post 28', 3, NOW()),
       ('The benefits of using blockchain for supply chain management', 5, 'This is the body of the post 29', 4, NOW()),
       ('The role of cryptocurrency in a cashless society', 4, 'This is the body of the post 30', 5, NOW()),
       ('Why you should hold your crypto for the long term', 5, 'This is the body of the post 31', 6, NOW()),
       ('The best cryptocurrency exchanges for beginners', 4, 'This is the body of the post 32', 7, NOW()),
       ('Why you should invest in privacy coins', 3, 'This is the body of the post 33', 8, NOW()),
       ('The potential of cryptocurrency for remittances', 4, 'This is the body of the post', 12, NOW()),
       ('How to use technical analysis to trade cryptocurrency', 4, 'This is the body of the post 35', 10, NOW()),
       ('Why you should diversify your crypto holdings beyond Bitcoin', 5, 'This is the body of the post 36', 11, NOW()),
       ('The impact of central bank digital currencies (CBDCs) on the crypto market', 4, 'This is the body of the post 37', 12, NOW()),
       ('How to use decentralized exchanges (DEXs) for trading', 4, 'This is the body of the post 38', 13, NOW()),
       ('Why NFTs are revolutionizing the art world', 5, 'This is the body of the post 39', 14, NOW()),
       ('The risks and rewards of investing in ICOs', 3, 'This is the body of the post 40', 15, NOW()),
       ('How to invest in cryptocurrencies with a small budget', 4, 'This is the body of the post 41', 16, NOW()),
       ('Why you should consider cryptocurrency as part of your retirement portfolio', 5, 'This is the body of the post 42', 17, NOW()),
       ('The future of gaming and NFTs', 4, 'This is the body of the post 43', 18, NOW()),
       ('How to use cryptocurrency for online purchases', 4, 'This is the body of the post 44', 19, NOW()),
       ('Why you should invest in altcoins with a strong community', 5, 'This is the body of the post 45', 10, NOW()),
       ('The potential of blockchain for identity verification', 4, 'This is the body of the post 46', 1, NOW()),
       ('How to protect your cryptocurrency investments during a market crash', 5, 'This is the body of the post 47', 2, NOW()),
       ('Why you should consider staking your crypto instead of hodling', 4, 'This is the body of the post 48', 3, NOW()),
       ('The impact of inflation on the value of cryptocurrency', 3, 'This is the body of the post 49', 4, NOW()),
       ('How to use cryptocurrency for charitable donations', 4, 'This is the body of the post 50', 5, NOW()),
       ('Why you should invest in renewable energy crypto projects', 4, 'This is the body of the post 51', 6, NOW()),
       ('The role of cryptocurrency in the gig economy', 3, 'This is the body of the post 52', 7, NOW()),
       ('How to use cryptocurrency for cross-border payments', 4, 'This is the body of the post 53', 8, NOW()),
       ('Why you should invest in emerging market cryptocurrencies', 5, 'This is the body of the post 54', 9, NOW()),
       ('The potential of blockchain for real estate transactions', 4, 'This is the body of the post 55', 8, NOW()),
       ('How to use cryptocurrency for international trade', 4, 'This is the body of the post 56', 5, NOW()),
       ('Why you should consider investing in decentralized finance (DeFi)', 5, 'This is the body of the post 57', 4, NOW()),
       ('The impact of government regulations on the cryptocurrency market', 3, 'This is the body of the post 58', 3, NOW()),
       ('How to use cryptocurrency for peer-to-peer lending', 4, 'This is the body of the post 59', 4, NOW()),
       ('Forum Guidelines', 6, 'This is the body of the post 7', 2, NOW());


INSERT INTO comments (post_id, content)
VALUES ( 5, 'Helo how are you');